services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/"]
      interval: 5s
      timeout: 3s
      retries: 30
