import builtins
from typing import Any

class BaseModel:
    def __init__(self, **data: Any) -> None: ...
    def dict(self, *args: Any, **kwargs: Any) -> builtins.dict[str, Any]: ...


def Field(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...
