version: "3.9"
networks: { aurora-net: { external: true } }
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: aurora-kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://aurora-kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@aurora-kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes: ["kafka_data:/var/lib/kafka/data"]
    networks: ["aurora-net"]

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: aurora-schema-registry
    ports: ["8081:8081"]
    environment:
      SCHEMA_REGISTRY_HOST_NAME: aurora-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://aurora-kafka:9092
    depends_on: ["kafka"]
    networks: ["aurora-net"]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: aurora-kafka-ui
    ports: ["8082:8080"]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: aurora-kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://aurora-schema-registry:8081
    depends_on: ["kafka","schema-registry"]
    networks: ["aurora-net"]

volumes: { kafka_data: {} }
