"""Add ETP models

Revision ID: d5a0df4808cf
Revises: 49d19e6c95b6
Create Date: 2025-07-13 22:02:40.098549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d5a0df4808cf"
down_revision: Union[str, Sequence[str], None] = "49d19e6c95b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tipo_obra", sa.String(), nullable=False),
        sa.Column("local", sa.String(), nullable=False),
        sa.Column("objetivo", sa.String(), nullable=False),
        sa.Column("valor_estimado", sa.Float(), nullable=True),
        sa.Column("prazo_estimado", sa.Integer(), nullable=True),
        sa.Column("conteudo_markdown", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("data_geracao", sa.DateTime(), nullable=False),
        sa.Column("data_atualizacao", sa.DateTime(), nullable=False),
        sa.Column("metadados", sa.String(), nullable=False),
        sa.Column("usuario_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_etps_status"), "etps", ["status"], unique=False)
    op.create_index(op.f("ix_etps_tipo_obra"), "etps", ["tipo_obra"], unique=False)
    op.create_index(op.f("ix_etps_usuario_id"), "etps", ["usuario_id"], unique=False)
    op.add_column("users", sa.Column("two_factor_secret", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("two_factor_enabled", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "two_factor_enabled")
    op.drop_column("users", "two_factor_secret")
    op.drop_index(op.f("ix_etps_usuario_id"), table_name="etps")
    op.drop_index(op.f("ix_etps_tipo_obra"), table_name="etps")
    op.drop_index(op.f("ix_etps_status"), table_name="etps")
    op.drop_table("etps")
    # ### end Alembic commands ###
