from typing import Any
DATABASE_URL: str
REDIS_URL: str
AURA_NEO4J_URI: str
AURA_NEO4J_USERNAME: str
AURA_NEO4J_PASSWORD: str
QDRANT_URL: str
KAFKA_BROKER: str
SCHEMA_REGISTRY_URL: str
__all__ = ["DATABASE_URL", "REDIS_URL", "AURA_NEO4J_URI", "AURA_NEO4J_USERNAME",
           "AURA_NEO4J_PASSWORD", "QDRANT_URL", "KAFKA_BROKER", "SCHEMA_REGISTRY_URL"]

DATABASE_URL: str
REDIS_URL: str
AURA_NEO4J_URI: str
AURA_NEO4J_USERNAME: str
AURA_NEO4J_PASSWORD: str
QDRANT_URL: str
KAFKA_BROKER: str
SCHEMA_REGISTRY_URL: str
__all__ = ["DATABASE_URL", "REDIS_URL", "AURA_NEO4J_URI", "AURA_NEO4J_USERNAME",
           "AURA_NEO4J_PASSWORD", "QDRANT_URL", "KAFKA_BROKER", "SCHEMA_REGISTRY_URL"]
