name: CI Template

'on':
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction
      - name: Run tests
        run: |
          pytest || true
      - name: Lint
        run: |
          ruff check . || true
      - name: Report status
        if: failure()
        run: echo "Build or tests failed for ${{ inputs.service_name }}"
