---
name: Lint - actionlint
on:
  pull_request:
  push:
    branches: [main, develop]
jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache actionlint binary
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/actionlint
          key: actionlint-bin-v1.7.1
      - name: Install actionlint (if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -euxo pipefail
          mkdir -p ~/.local/bin
          curl -sSL -o /tmp/actionlint.tgz \
            https://github.com/rhysd/actionlint/releases/download/v1.7.1/actionlint_1.7.1_linux_amd64.tar.gz
          tar -xzf /tmp/actionlint.tgz -C ~/.local/bin actionlint
          chmod +x ~/.local/bin/actionlint
          ~/.local/bin/actionlint --version
      - name: Run actionlint
        env:
          PATH: ~/.local/bin:${{ env.PATH }}
        run: |
          actionlint -color -shellcheck='' -pyflakes=''
