---
name: CI - Crawler Smoke
on:
  push:
    branches: [main, develop, feat/**, fix/**]
  pull_request:
    branches: [main, develop]
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: |
            **/package-lock.json
            **/package.json

      - name: Install deps
        run: npm ci

      - name: Smoke check
        run: |
          if npm run -s smoke; then
            echo "Smoke OK"
          else
            echo "No 'smoke' script; running a lightweight default."
            node -e "console.log('Crawler smoke placeholder ✅')"
          fi
