name: ci-crawler-smoke

on:
  workflow_dispatch:
  push:
    branches: [ops/**, feature/**]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Crawler smoke placeholder
        run: echo "Crawler smoke OK"