name: ci-crawler-js-e2e
on:
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "crawler-js-e2e placeholder OK"