name: Crawler render compare (dry-run)

'on':
  pull_request:
    paths:
      - "aurora_platform/modules/crawler/rn_contacts/**"
      - "scripts/run_rn_contacts.py"
      - "scripts/compare_render_reports.py"
      - "configs/missions/*.yml"
  workflow_dispatch: {}

jobs:
  render-compare:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TESTING: "1"
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run smokes (dry-run) to produce manifests
        run: |
          python scripts/run_rn_contacts.py --mission configs/missions/rn_js_heavy_smoke.yml --out .artifacts/outputs --dry-run
          python scripts/run_rn_contacts.py --mission configs/missions/rn_js_heavy_smoke_auto.yml --out .artifacts/outputs --dry-run

      - name: Build render_compare.csv
        run: |
          mkdir -p .artifacts/reports
          python scripts/compare_render_reports.py .artifacts/outputs --csv .artifacts/reports/render_compare.csv
          echo "Preview:"
          head -n 5 .artifacts/reports/render_compare.csv || true

      - name: Upload artifact (render_compare.csv)
        uses: actions/upload-artifact@v4
        with:
          name: render-compare
          path: .artifacts/reports/render_compare.csv
          if-no-files-found: warn
