---
name: ci
on:
  push:
    branches: [main, develop, ops/**, feature/**]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
      - name: Install base tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || true
          pip install ruff pyright pytest pytest-cov requests

  guard-duplicates:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guard duplicate roots
        run: python tools/check_duplicate_packages.py

  lint-type:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
      - name: Install deps (lint)
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyright
      - name: Ruff
        run: ruff check .
      - name: Pyright
        run: pyright

  unit-tests:
    needs: [guard-duplicates, lint-type]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    services:
      qdrant:
        image: qdrant/qdrant:v1.7.4
        ports: ["6333:6333"]
        options: >-
          --health-cmd="curl -fsS http://localhost:6333/ready || exit 1"
          --health-interval=5s --health-timeout=2s --health-retries=24

    env:
      QDRANT_URL: http://localhost:6333
      ENABLE_QDRANT_TESTS: "1"
      ENABLE_NET_TESTS: "0"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install requests

      - name: Wait for Qdrant
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:6333/ready > /dev/null; then
              echo "Qdrant is ready"; exit 0
            fi
            sleep 1
          done
          echo "Qdrant not ready"; exit 1

      - name: PyTest
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=. --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --junit-xml=pytest-report.xml
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
          if-no-files-found: warn
      - name: Upload junit artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.python-version }}
          path: pytest-report.xml
          if-no-files-found: warn
