name: ci
on:
  push:
    branches: [main, develop, ops/**, feature/**]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v1

  setup:
    needs: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install base tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || true
          pip install ruff pyright pytest pytest-cov requests

  guard-duplicates:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Guard duplicate roots
        run: python tools/check_duplicate_packages.py

  lint-type:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Ruff
        run: ruff check .
      - name: Pyright
        run: pyright

  unit-tests:
    needs: [guard-duplicates, lint-type]
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant:v1.7.4
        ports: ["6333:6333"]
        options: >-
          --health-cmd="curl -fsS http://localhost:6333/ready || exit 1"
          --health-interval=5s --health-timeout=2s --health-retries=24

    env:
      QDRANT_URL: http://localhost:6333
      ENABLE_QDRANT_TESTS: "1"
      ENABLE_NET_TESTS: "0"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install requests

      - name: Wait for Qdrant
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:6333/ready > /dev/null; then
              echo "Qdrant is ready"; exit 0
            fi
            sleep 1
          done
          echo "Qdrant not ready"; exit 1

      - name: PyTest
        run: pytest -q --maxfail=1 --disable-warnings