name: CODEOWNERS Guard
on:
  pull_request:
    paths:
      - ".github/CODEOWNERS"
      - "**/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure CODEOWNERS exists and non-empty
        run: |
          test -s .github/CODEOWNERS || { echo "Missing or empty .github/CODEOWNERS"; exit 1; }
      - name: Show CODEOWNERS head
        run: head -n 20 .github/CODEOWNERS || true
