---
name: ci-docker-presence
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch: {}

jobs:
  docker-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check docker CLI
        run: |
          if ! command -v docker >/dev/null; then
            echo "docker CLI missing (would trigger exit 127 in dependent jobs)" >&2
            exit 1
          fi
          docker version --format '{{.Client.Version}}'
      - name: Check basic run
        run: |
          docker run --rm hello-world >/dev/null 2>&1 || echo "hello-world run skipped (no daemon?)"
