name: e2e
on:
  workflow_dispatch: {}
  pull_request:
    types: [labeled]

jobs:
  e2e:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'e2e') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "E2E placeholder OK"