name: EXEMPLO Guard

'on':
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "README*"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: List changed files
        id: diff
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
            **/*.yml
            **/*.yaml
            **/*.json
            **/*.txt
            **/*.md
          files_ignore: |
            docs/**
            tests/fixtures/**
            node_modules/**
            dist/**
            build/**
            artifacts/**

      - name: Scan changed files for EXEMPLO markers
        run: |
          set -euo pipefail
          PATTERN='(<<<EXEMPLO_INICIO>>>|<<<EXEMPLO_FIM>>>|\bEXEMPLO\b)'
          found=0
          for f in ${{ steps.diff.outputs.all_changed_files }}; do
            # pular binários grandes
            if [ -f "$f" ] && [ $(wc -c <"$f") -gt $((2*1024*1024)) ]; then
              echo "[ci] Skip $f (>2MB)"
              continue
            fi
            if command -v rg >/dev/null 2>&1; then
              rg -n -E "$PATTERN" --pcre2 "$f" && found=1 || true
            else
              grep -nE "$PATTERN" "$f" && found=1 || true
            fi
          done
          if [ "$found" -eq 1 ]; then
            echo "::error::Marcadores EXEMPLO detectados no diff da PR."
            exit 1
          fi
          echo "[ci] EXEMPLO guard passed."
