name: guard-duplicate-packages
on:
  pull_request:
    branches: ["**"]
    paths:
      - "**.py"
      - "tools/**"
      - ".github/workflows/guard-dup-folders.yml"

jobs:
  duplicate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run duplicate package guard
        run: |
          python tools/check_duplicate_packages.py
