name: hrm-smoke

on:
  workflow_dispatch:
  push:
    branches: [ops/**, feature/**]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "HRM smoke OK"