---
name: MVP1 - Ingest
on:
  workflow_dispatch:
  push:
    branches: [main, develop]
jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
      - name: Install Poetry
        run: pipx install poetry==1.8.3
      - name: Install deps
        run: poetry install --no-interaction --no-ansi --with dev
      - name: Run ingest
        shell: bash
        run: |
          set -euo pipefail
          if poetry run python -m aurora_ingest.run; then
            echo "Ingest finished ✅"
          else
            echo "Fallback: no module; running placeholder."
            PY64='cHJpbnQoIkZhbGxiYWNrIG1vZHVsbyBhdXJvcmFfaW5nZXN0LmJhc2UiKQ=='
            echo "$PY64" | base64 -d | python3 -
          fi
