name: "MVP1 - Ingest Pipeline"

'on':
  workflow_dispatch:
  push:
    branches:
      - main
      - "feat/**"
    paths:
      - "ingest/**"
      - ".github/workflows/mvp1-ingest.yml"

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run placeholder
        run: echo "Ingest pipeline placeholder - adjust to project specifics"
name: "MVP1 - Ingest Pipeline"

'on':
  workflow_dispatch:
  push:
    branches:
      - main
      - "feat/**"
    paths:
      - "ingest/**"
      - ".github/workflows/mvp1-ingest.yml"

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run placeholder
        run: echo "Ingest pipeline placeholder - adjust to project specifics"
        options: >-
          --health-cmd="wget -qO- http://localhost:6333/readyz || exit 1"
          --health-interval=10s
          --health-timeout=3s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Wait for Qdrant
        run: |
          for i in {1..60}; do
            if curl -fs http://localhost:6333/readyz >/dev/null; then
              echo "Qdrant is ready"
              exit 0
            fi
            sleep 2
          done
          echo "Qdrant did not become ready"
          exit 1

      - name: Run ingest tests
        env:
          QDRANT_URL: http://localhost:6333
        run: pytest -v tests/ingest/
name: "MVP1 1 Ingest Pipeline"

'on':
  workflow_dispatch:
  push:
    branches:
      - main
      - "feat/**"
    paths:
      - "ingest/**"
      - ".github/workflows/mvp1-ingest.yml"

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333
          - 6334:6334
        options: >-
          --health-cmd="wget -qO- http://localhost:6333/readyz || exit 1"
          --health-interval=10s
          --health-timeout=3s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Wait for Qdrant
        run: |
          for i in {1..60}; do
            if curl -fs http://localhost:6333/readyz >/dev/null; then
              echo "Qdrant is ready"
              exit 0
            fi
            sleep 2
          done
          echo "Qdrant did not become ready"
          exit 1

      - name: Run ingest tests
        env:
          QDRANT_URL: http://localhost:6333
        run: pytest -v tests/ingest/
name: "MVP1 – Ingest Pipeline"

'on':
  workflow_dispatch:
  push:
    branches:
      - main
      - "feat/**"
    paths:
      - "ingest/**"
      - ".github/workflows/mvp1-ingest.yml"

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333
          - 6334:6334
        options: >-
          --health-cmd="wget -qO- http://localhost:6333/readyz || exit 1"
          --health-interval=10s
          --health-timeout=3s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Wait for Qdrant
        run: |
          for i in {1..60}; do
            if curl -fs http://localhost:6333/readyz >/dev/null; then
              echo "Qdrant is ready"
              exit 0
            fi
            sleep 2
          done
          echo "Qdrant did not become ready"
          exit 1

      - name: Run ingest tests
        env:
          QDRANT_URL: http://localhost:6333
        run: pytest -v tests/ingest/
