name: mvp1-ingest

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run ingest
        run: echo "Ingest pipeline placeholder"
