---
name: MVP1 - Ingest Pipeline
on:
  workflow_dispatch:
  push:
    branches: [main, develop, feat/**]
jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports: ["6333:6333", "6334:6334"]
        options: >-
          --health-cmd "wget -qO- http://localhost:6333/readyz || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps
        run: |
          poetry install --no-interaction --no-ansi
        working-directory: .

      - name: Wait Qdrant healthy
        run: |
          for i in $(seq 1 60); do
            if curl -sf http://localhost:6333/readyz >/dev/null; then
              echo "Qdrant ready"; exit 0
            fi
            sleep 2
          done
          echo "Qdrant not ready in time"; exit 1

      - name: Run ingestion
        env:
          QDRANT_URL: http://localhost:6333
        run: |
          if poetry run python -m aurora_ingest.run; then
            echo "Ingest finished ✅"
          else
            echo "Fallback: no module; running placeholder check."
            python - <<'PY'
            import urllib.request
            urllib.request.urlopen("http://localhost:6333/readyz")
            print("Qdrant reachable ✅")
            PY
          fi
