name: Ops KG Health

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets presence (masked)
        shell: bash
        run: |
          check() { if [ -n "$1" ]; then echo "$2=SET"; else echo "$2=MISSING"; fi; }
          check "${{ secrets.AURA_NEO4J_URI }}" AURA_NEO4J_URI
          check "${{ secrets.AURA_NEO4J_USERNAME }}" AURA_NEO4J_USERNAME
          check "${{ secrets.AURA_NEO4J_PASSWORD }}" AURA_NEO4J_PASSWORD
          check "${{ secrets.QDRANT_URL }}" QDRANT_URL
          check "${{ secrets.KAFKA_BROKER }}" KAFKA_BROKER
          check "${{ secrets.SCHEMA_REGISTRY_URL }}" SCHEMA_REGISTRY_URL
