name: Ops Audit (lint + yaml)
on:
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install ruff
        run: pip install ruff
      - name: Ruff check
        run: ruff check .
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic YAML parse
        run: |
          python - <<'PY'
          import sys, yaml, pathlib
          bad=[]
          for p in pathlib.Path(".github/workflows").glob("*.yml"):
              try:
                  yaml.safe_load(p.read_text(encoding="utf-8"))
              except Exception as e:
                  bad.append((str(p), str(e)))
          if bad:
              print("YAML errors:")
              for f,e in bad: print(f, "->", e)
              sys.exit(1)
          PY
