name: ops-kg-health
on:
  workflow_dispatch:

# Defina variáveis de repositório aqui (apenas UMA vez)
env:
  AURA_NEO4J_URI:       ${{ vars.AURA_NEO4J_URI }}
  AURA_NEO4J_USERNAME:  ${{ vars.AURA_NEO4J_USERNAME }}
  QDRANT_URL:           ${{ vars.QDRANT_URL }}
  KAFKA_BROKER:         ${{ vars.KAFKA_BROKER }}
  SCHEMA_REGISTRY_URL:  ${{ vars.SCHEMA_REGISTRY_URL }}

jobs:
  health:
    runs-on: ubuntu-latest

    # Defina apenas os SEGREDOS aqui (não duplique as chaves acima)
    env:
      AURA_NEO4J_PASSWORD: ${{ secrets.AURA_NEO4J_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Show env presence (masked)
        run: |
          printf "AURA_NEO4J_URI=%s\n" "$AURA_NEO4J_URI"
          printf "AURA_NEO4J_USERNAME=%s\n" "$AURA_NEO4J_USERNAME"
          printf "QDRANT_URL=%s\n" "$QDRANT_URL"
          printf "KAFKA_BROKER=%s\n" "$KAFKA_BROKER"
          printf "SCHEMA_REGISTRY_URL=%s\n" "$SCHEMA_REGISTRY_URL"
          if [ -z "${AURA_NEO4J_PASSWORD}" ]; then
            echo "AURA_NEO4J_PASSWORD is EMPTY"
          else
            echo "AURA_NEO4J_PASSWORD is SET"
          fi

      - name: Placeholder health checks
        run: |
          echo "TODO: add curl/tcp checks:"
          echo "- curl -fsS ${QDRANT_URL}/ready"
          echo "- curl -fsS ${AURA_NEO4J_URI} (auth via envs)"
          echo "- nc -z $(echo ${KAFKA_BROKER} | cut -d: -f1) $(echo ${KAFKA_BROKER} | cut -d: -f2)"