name: PR Housekeeping
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
permissions:
  pull-requests: write
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo
            const pr = context.payload.pull_request
            await github.rest.issues.addAssignees({
              owner, repo, issue_number: pr.number, assignees: [pr.user.login]
            })
