name: tests
'on':
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  connector-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pipx install poetry
      - name: Validate Poetry lockfile
        run: |
          poetry install --no-interaction --no-root
          poetry check
      - name: Install deps
        run: |
          poetry install --no-interaction --no-root
          poetry add tenacity --lock
          poetry install --no-interaction --no-root
      - name: Run tests (connector)
        env:
          PYTHONPATH: .
          TESTING: "1"
        run: |
          poetry run pytest -q tests/connectors/test_connector_tce_rn.py
