name: validate-compose
'on':
  pull_request:
    branches: [ main, master ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker setup
        uses: docker/setup-buildx-action@v3
      - name: Validate docker-compose.yml
        run: |
          docker compose version
          docker compose config -q
